### ISSUE TITLE
New Leaf 5 PM doesn't loop well

### ISSUE THREAD

**Issue by Azekthi** [mn6/nook#10]
I've just downloaded this extension on Firefox and I love it! Only thing I'm noticing right now is that the New Leaf 5 PM loop isn't that good, it fades out before starting again when it doesn't actually fade out in the game. I'm not sure yet if this is also the case for all the other tracks, but if it is, I'd really hope for a better edit of the tracks to have them loop better.

**Comment by mn6** [comment]
This is done because of the background bass in the song that isn't present in the beginning. This song isn't very loopable without removing essential sections of the music.
