### ISSUE TITLE
Grandfathermode

### ISSUE THREAD

**Issue by MrShuzo** [mn6/nook#14]
If you activate Grandfathermode and you selected everything of the Grandfathermode the add-on won't play music anymore after deactivating Grandfathermode. You can only fix this by reinstalling the add-on.

**Comment by mn6** [comment]
Hey there, do you mind providing further details? Steps to reproduce the issue would be great.

**Comment by MrShuzo** [comment]
Of course: First of all you open the plugin. You can now start playing the music or you don't, doesn't matter for the bug itself. After that you activate the grandfather-mode by clicking on the checkbox but without having it activated anytime before or changing the active hours of the grandfather-mode. If you then deactivate the grandfather-mode and try to play the music again (doesn't matter which game) it won't start playing till you reinstall the plug-in.
EDIT: Even if you change the grandfather-mode active hours it won't play anymore after deactivating grandfather-mode.

**Comment by MrScottyTay** [comment]
Simply turning on grandfather mode for me stops it from playing any audio.

**Comment by mn6** [comment]
Seems what's being experienced is the intended functionality of grandfather mode, it's meant to work like a grandfather clock.

**Comment by MrScottyTay** [comment]
So grandfather mode is supposed to stop ALL audio from working? just so you know it DOES NOT play on the hour either, it just doesn't work anymore. I'm pretty sure that's not the intended functionality.

**Comment by mn6** [comment]
Have you tried a fresh reinstall of the extension? I don't seem to have this issue in my testing
