### ISSUE TITLE
Local rain and snow & hourly theme

### ISSUE THREAD

**Issue by niels-beier** [mn6/nook#15]
Hey there,
I have two suggestions I would like to present to you. First of all, is it possible to add a feature which plays rain and snow music whenever it is raining or snowing at yours? As a user you would first select the country you live in and secondly paste your postal code into a field.
Secondly it would be very nice to hear an hourly theme between hours, just like in the Animal Crossing games. Maybe the user would be able to customize this theme like in the games at the post office.
Best regards
shuzo

**Comment by Azekthi** [comment]
I would love both of these features.

Unfortunately, per #9 the dev doesn't feel like adding the customizable town tune hourly theme 🤷‍♂️

**Comment by mn6** [comment]
Thanks for the suggestions! I'll add local weather checks to the to-do list.

**Comment by mn6** [comment]
Adding the town tune customizer to the desktop version.

**Comment by mn6** [comment]
Added this in the desktop version.

https://github.com/mn6/nook-desktop/commit/2b6c7d10b445ef4702ced8bb9115450ad8da4039
