### ISSUE TITLE
Pocket Camp themes

### ISSUE THREAD

**Issue by Azekthi** [mn6/nook#16]
I would enjoy seeing the addition of the Animal Crossing: Pocket Camp themes. They last a few hours each, but they're not all day long. They also have rain and snow variants.

**Comment by mn6** [comment]
Thanks for the suggestion! I'm not familiar with Pocket Camp -- do you know when the themes play during the day?

**Comment by Azekthi** [comment]
According to a Japanese guide book, the themes play at these times:

Morning: 5:00 AM ~ 8:59 AM
Day/Noon: 9:00 AM ~ 4:59 PM
Evening: 5:00 PM ~ 6:59 PM
Night: 7:00 PM ~ 4:59 AM
