### ISSUE TITLE
Add K.K. Bubblegum?

### ISSUE THREAD

**Issue by CSMJ31** [mn6/nook#20]
Hi love what you made here I was just wondering if at some point K.K. Bubblegum would be getting add to the K.K. Slider Playlist. 
Me and some friends would really enjoy it if we could get that song add?

**Comment by mn6** [comment]
Sure can! I'll add it in a few minutes and it'll be in the next release.

**Comment by CSMJ31** [comment]
Awesome! Thank you, I look forward to listening to it when it comes out!
