### ISSUE TITLE
switch between rain + thunder

### ISSUE THREAD

**Issue by yyoonji** [mn6/nook#21]
hi !! i rlly love this extension, ty for bringing it out,,, i just wanted to ask if it was possible to separate the rain and thunder ?? i love rain but thunder sets out my anxiety a lot,,, so im kind of peaceful but on the edge using this extension. i feel like this might also be something that a lot of other people would benefit to !!

**Comment by mn6** [comment]
Sure thing! Hadn't considered this, will find a rain track that features no thunder. Thanks for the suggestion!

**Comment by mn6** [comment]
Will have a thunderless option in Nook Desktop!

**Comment by mn6** [comment]
Added thunderless rain in the desktop version!

https://github.com/mn6/nook-desktop/commit/2b6c7d10b445ef4702ced8bb9115450ad8da4039
