### ISSUE TITLE
Request: Shuffle between games?

### ISSUE THREAD

**Issue by ZarikTH** [mn6/nook#22]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
I would like an option to shuffle between game soundtracks every hour, if possible! I don't know how much the vibes would change but I think it would be cool!

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ZarikTH** [comment]
games most likely wouldn't shuffle well together

**Comment by AbbieDoobie** [comment]
I think this should be reopened. Games may not shuffle together perfectly, but I would still like to have the option. 

If "all" is selected, or a checkbox ticked, then every hour a different game will be selected.
