### ISSUE TITLE
Music Stops Working [Grandfather + New Horizons]

### ISSUE THREAD

**Issue by ItsDatSpicymeme** [mn6/nook#25]
When switching to the New Horizons music and having or already had turned on grandfather mode, the music stops working and I either have to manually in Chorme's extension settings turn it off and on again, or uninstall and reinstall it entirely.

Chrome: Version 85.0.4183.121 (Official Build) (64-bit)
Windows 10

**Comment by proconsult** [comment]
have same problem with Firefox 88.0 64-Bit

**Comment by mn6** [comment]
To be fixed in the desktop version

**Comment by mn6** [comment]
Fixed in desktop version!

https://github.com/mn6/nook-desktop/commit/2b6c7d10b445ef4702ced8bb9115450ad8da4039
