### ISSUE TITLE
Add to Microsoft Edge Addons

### ISSUE THREAD

**Issue by MaXfAa** [mn6/nook#26]
I am using the Microsoft Edge browser and I propose to add the nook extension also to the Microsoft Edge Addons (https://microsoftedge.microsoft.com/addons/)

**Additional context**
The extension is already available on the Chrome Web Store but why not add it on the Microsoft Edge Addons ?(https://developer.microsoft.com/en-us/microsoft-edge/extensions/)

**Comment by mn6** [comment]
Extension will soon be unsupported as an extension, working on a desktop version to fix this
