### ISSUE TITLE
Animal Crossing: Taking Root By Scruffy

### ISSUE THREAD

**Issue by TheOnlyThing** [mn6/nook#31]
A youtuber by the name of Scruffy composed a song for each hour in a animal crossing game game he made up

https://www.youtube.com/watch?v=f8pYxhDEgfg&list=PLQY6PNl6p3MYWVZa5R5Emdi-CxgM40Scm&index=1

The music is really good so it would work great in the extension!

**Comment by LupusHacker** [comment]
Yes! I've been listening to that alot lately, and I love how each track sounds like a mash-up from each game. 😌

**Comment by mn6** [comment]
Unfortunately wouldn't be able to do this -- wouldn't want to subtract from the creator's revenue and viewership numbers
