### ISSUE TITLE
Ability to switch between Aircheck/Live only K.K. songs, and to be able to skip through them

### ISSUE THREAD

**Issue by LupusHacker** [mn6/nook#32]
**Is your feature request related to a problem? Please describe.**
The list is somewhat jumbled for the list of KK songs, so this is more to tidy the list up; Simple media controls for K.K. songs (play/pause, skip, shuffle)

**Describe the solution you'd like**
Having them in a subcategory of Live/Aircheck, and a check in front of both lists (Or just a toggle that switches between the two.); Having media controls pop up when it's set to "Always" for the KK Slider frequency.

**Describe alternatives you've considered**
Going through the entire list and unchecking them one at a time; Pausing and unpausing resets the music stream when it's set to just K.K songs, but that seems somewhat unorthodox.

**Comment by mn6** [comment]
Added in https://github.com/mn6/nook/commit/df0eca735e3d3c84dd1ab19e22e2be81e6ba51ae
