### ISSUE TITLE
In-game rain/snow sound effect for hourly

### ISSUE THREAD

**Issue by LupusHacker** [mn6/nook#33]
**Is your feature request related to a problem? Please describe.**
I've actually listen to that rain ASMR that's set for the rain option. lol

**Describe the solution you'd like**
Somehow pull the rain sounds from the game. i.e. use the separate tracks for each (would probably add another load onto the file stream tho. :/)  

**Describe alternatives you've considered**
Suck it up and be fine with it not being the right rain. lol

**Comment by mn6** [comment]
Working on this in the new desktop app version. Thanks for your suggestion!

**Comment by mn6** [comment]
Added in desktop version!

https://github.com/mn6/nook-desktop/commit/2b6c7d10b445ef4702ced8bb9115450ad8da4039
