### ISSUE TITLE
Add a random mode 

### ISSUE THREAD

**Issue by axelludwig** [mn6/nook#34]
**Is your feature request related to a problem? Please describe.**
I use this extension during work hours, so I always have the same songs everyday at the same time.

**Describe the solution you'd like**
You could add a random mode that creates a playlist of all songs from the selected game and plays them randomly.

**Additional context**
It could be a very simple checkbox that activates this mode.

Anyway, thank you for this extension !! It works well and I like its design 👍

**Comment by mn6** [comment]
Added in https://github.com/mn6/nook/commit/df0eca735e3d3c84dd1ab19e22e2be81e6ba51ae
