### ISSUE TITLE
Add Pocket Camp music (Sunny, Rainy, Snowy)

### ISSUE THREAD

**Issue by LupusHacker** [mn6/nook#37]
Pocket Camp was pretty forgettable in terms of gameplay IMO, but I stilled liked the "hourly" themes. And it was still pretty fun to play- although not for long periods of time.

Considering there was only three types of environment music (Sunny, Rainy, Snowy) along with the 4 time differences (morning, afternoon, evening, night)- I think it would be pretty easy to implement. It would get a tad annoying to listen to the same music for 4 hours at time before a transition, but it would still be a cool option. ^^

**Comment by mn6** [comment]
Added in desktop version.

https://github.com/mn6/nook-desktop/commit/2b6c7d10b445ef4702ced8bb9115450ad8da4039
