### ISSUE TITLE
Add cicada sounds

### ISSUE THREAD

**Issue by dejakob1** [mn6/nook#7]
Could you please find a way to add cicada sounds?
Perhaps a selection of all the different cicadas with toggles.
So multiple can be mixed.

**Comment by Nemura** [comment]
Would love to see this as well.

**Comment by mn6** [comment]
Interesting idea! Cicada sounds from the game or real ones? Could add a dropdown in place of the "Rain Volume" label and add a variety of different white noise and nature sounds.

**Comment by dejakob1** [comment]
I think those of New Leaf will have the best quality. I'd go with that!
Dropdown sounds nice as well.

**Comment by mn6** [comment]
I've decided to stick with exclusively rain sounds for the time being, an ambient noise dropdown would make the UI a little clunky and not as straightforward.
