### ISSUE TITLE
Broken checkboxes on Firefox

### ISSUE THREAD

**Issue by Nemura** [mn6/nook#8]
**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 68.0 (64-bit)

It seems the checkboxes in the extension are broken. I am referring to the checkboxes used to enable/disable Grandfather Mode, select times, and select K.K. Slider songs.

![xug8gvEbJR](https://user-images.githubusercontent.com/3428863/61798714-1b379e00-ae2a-11e9-9e66-9d693f0b521e.png)
![fZRpjpdWRd](https://user-images.githubusercontent.com/3428863/61798715-1b379e00-ae2a-11e9-844a-88a889e597d3.png)
![mslrCR89wi](https://user-images.githubusercontent.com/3428863/61798716-1b379e00-ae2a-11e9-8c7a-6496958afd0b.png)

**Comment by mn6** [comment]
Strange, will look into this in the morning. Doesn't seem to happen in Chrome, so maybe just a styling issue.

**Comment by Azekthi** [comment]
On Firefox 69.0.3, the checkboxes are displaying just fine upon initial installation.

**Comment by Nemura** [comment]
I can confirm this is fixed in updated versions.
