### ISSUE TITLE
Inspiration from other project

### ISSUE THREAD

**Issue by Nemura** [mn6/nook#9]
I don't know if you know this, but there's another animal crossing music extension on github on which develeopment has ceased. You could take quite some inspiration from this as it has a great amount of functionality. It would be really cool if you could also implement the option for town tunes.

https://github.com/Nemura/Animal-Crossing-Music-Extension

**Comment by Azekthi** [comment]
The only big thing from that older extension is customizable town tunes, though I do see there was a suggestion made about local weather syncing to determine when to play rain and snow tunes, I would love to see that too.

**Comment by mn6** [comment]
This extension was made as sort of an enhanced version of the one linked -- town tunes were in development but I decided against it in favor of working on perfecting the base functionality.
